### PR TITLE
Attempt to auto-resize source icons when packaging macOS bundles

### PR DESCRIPTION
**Pull request by oluseyi**
RE https://github.com/burtonageo/cargo-bundle/issues/22

This does not guarantee that a valid icon type will result. If you submit a 1024x1024 it will fail, even though it is square and dimensions are powers of two because the largest supported dimension is 512x512.

Also, if you submit, say, a 400x400 and a 256x256 version of your icon, it is undefined which will be represented in the final ICNS file.

### CODE REVIEW

**Comment by mdsteele** [comment]
Nice!  One thought though: if the user supplies both a 400x400 and a 256x256 icon, rather than leaving it undefined, it seems like it would be better to reliably use the exactly-256x256 one for the 256x256 slot, rather than the resized 400x400 one.  One way to do this might be to make two passes over the list of supplied icons, first taking the ones that are already a supported size, and on the second pass using resized images to fill in any missing sizes.  (The deb bundle icon implementation does something similar, where it uses only PNG files in the first pass, and in a second pass converts from non-PNG image types to PNG to fill in missing sizes.)

**Comment by oluseyi-cnbc** [comment]
Hey @mdsteele. Yeah, I did think about that but I deferred implementation at the time. Thinking about it now, we can add non-ICNS-dimension files to a separate list and then process that after we've added all the supported files.

I'll make some adjustments and push in a bit.

**Comment by oluseyi** [comment]
Ok, that took longer than expected. I actually went down an alternate path, trying to write something that was more "idiomatically Rust-y," but that got me into trouble with `try!`'s automatic propagation of `Result<T>` errors…

Anyway, simple enhancement: using the heuristic of "dimensions are square, dimension is a power of 2, and dimension is less than 1024", push images that will need resizing into a `Vec`, then iterate over it and use existing `icns::IconFamily::has_icon_with_type` test to prevent overwriting an original matching image.

**Comment by mdsteele** [comment]
Looks better, thanks!  Could you resolve the merge conflicts (and run rustfmt if you haven't already)?

**Comment by oluseyi** [comment]
@mdsteele Done and done.

**Pull request merged**
