### PR TITLE
Created the `linux` module to improve the code structure

### PR DESCRIPTION
**Pull request by anas-elgarhy**
Ceate a separate `linux` module and separate the common functions into one separated file

This PR is uncompleted yet, but I opened it to track the progress and to discussion.

I had to implement the `Default` trait for the `Settings` and the `PackageSettings` and the `BundleSettings` structs to create tests, but I'm not sure if this is the beast way or there are the best way to make this without implement the `Default` trait?

- Close: #129 

### TODO:
- [x] Create a `linux` module and a `common` file for Linux
- [x]  move the `deb_bundle` into `linux` module
- [x] move the `rpm_bundle` into `linux` module
- [x] implement the `Default` traite for the `Settings` and the `PackageSettings` and the `BundleSettings` structs to create tests
- [x] Create a test for the `generate_desktop_file` function
- [x] Create a test for the `tar_and_gzip_dir` function, and refactor it if need it
- [x] Create a test for the `create_tar_from_dir` function, and refactor it if need it (covered with the  `tar_and_gzip_dir` function test)
- [x] Create a test for the `create_file_with_data` function, and refactor it if need it
- [x] Create a test for the `total_dir_size` function, and refactor it if need it
- [x] Refactor the `generate_icon_files` function, ~and create unit-test for it~
- [x] Separate the `generate_md5sum` function from the `deb_bundle.rs` file to the `common.rs` file, and create a test for it

### CODE REVIEW

**Comment by SergioRibera** [comment]
@anas-elgarhy do you need help? I just discovered this project and was thinking that it would be a good idea to accommodate it a little better in order to be able to scale on the other bundle systems out there  and I see that you are already working on it

**Comment by anas-elgarhy** [comment]
Yes, I'm not available now to work on code unfortunately, so I really appreciate if you can help me, and review this pr <https://github.com/anaselgarhy/cargo-bundle/pull/1> or if u fix the conflicts

And thanks in advance.

**Comment by anas-elgarhy** [comment]
I had to remove the implementation of the `Default` trait for the `Settings`  and the `BundleSettings` structs in older to merge the base, because @slonopotamus removes the `PackageSettings` struct in #138 and uses the `Package` struct from the `cargo_metadata` crate which is not implementing the `Default` trait and I think is not ideal if I implemented it.

But I still need an easy way to create an instance from the `Settings` struct in a some tests. So maybe I go to use the `test-context` crate, or I'll break down the functions and methods that's needing the `Settings` struct into small inline functions/methods, and test them.

* Merging PR: <https://github.com/anaselgarhy/cargo-bundle/pull/3>

**Comment by SergioRibera** [comment]
> I had to remove the implementation of the trait for the and the structs in older to merge the base, because @slonopotamus removed the struct in #138 and used the struct from the crate which is not implementing the trait and I think is not ideal if I implemented it.`Default``Settings``BundleSettings``PackageSettings``Package``cargo_metadata``Default`
> 
> But I still need an easy way to create an instance from the struct in a some tests. So maybe I go to use the crate, or I'll break down the functions and methods that's needing the struct into small inline functions/methods, and test them.`Settings``test-context``Settings`
> 
> * Merging PR: [Resolve the conflicts and merge the master branch anaselgarhy/cargo-bundle#3](https://github.com/anaselgarhy/cargo-bundle/pull/3)

I think I can help you here too, let me check out that pr and see if I can add some details

**Comment by anas-elgarhy** [comment]
> I think I can help you here too, let me check out that pr and see if I can add some details

Nice, u can also take a look at the `test_generate_desktop_file` test, because this is the only place I use the `default` in.

I wonder if this test is not quite important, and we can just remove it

**Comment by anas-elgarhy** [comment]
I think it's a good idea to just ignore test `generate_desktop_file` function for now

**Comment by anas-elgarhy** [comment]
The test action has a *bug*, It's using the stable rust, while we use nightly features
 image

**Comment by anas-elgarhy** [comment]
I can replace the `assert_matches` with the normal `assert` macro instead

**Comment by anas-elgarhy** [comment]
@mdsteele Please don't forget to review this sad PR when you have a time

**Comment by anas-elgarhy** [comment]
image

**Pull request merged**
